### ISSUE TITLE
Error - Unhandled Exception

### ISSUE THREAD

**Issue by mmenanno** [eugenio412/PogomBOT#2]
I can't seem to get this to run.

```
2016-08-17 11:42:43,719 - telegram.ext.updater - ERROR - unhandled exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/telegram/ext/updater.py", line 104, in _thread_wrapper
    target(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/telegram/ext/updater.py", line 215, in _start_polling
    self._bootstrap(bootstrap_retries, clean=clean, webhook_url='')
  File "/usr/local/lib/python3.5/site-packages/telegram/ext/updater.py", line 319, in _bootstrap
    self.bot.setWebhook(webhook_url=webhook_url, certificate=cert)
  File "/usr/local/lib/python3.5/site-packages/telegram/bot.py", line 121, in decorator
    result = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/telegram/bot.py", line 1263, in setWebhook
    result = request.post(url, data, timeout=kwargs.get('timeout'))
  File "/usr/local/lib/python3.5/site-packages/telegram/utils/request.py", line 235, in post
    **urlopen_kwargs)
  File "/usr/local/lib/python3.5/site-packages/telegram/utils/request.py", line 178, in _request_wrapper
    raise Unauthorized()
telegram.error.Unauthorized: Unauthorized
Exception in thread updater:
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.5.2/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python3/3.5.2/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.5/site-packages/telegram/ext/updater.py", line 104, in _thread_wrapper
    target(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/telegram/ext/updater.py", line 215, in _start_polling
    self._bootstrap(bootstrap_retries, clean=clean, webhook_url='')
  File "/usr/local/lib/python3.5/site-packages/telegram/ext/updater.py", line 319, in _bootstrap
    self.bot.setWebhook(webhook_url=webhook_url, certificate=cert)
  File "/usr/local/lib/python3.5/site-packages/telegram/bot.py", line 121, in decorator
    result = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/telegram/bot.py", line 1263, in setWebhook
    result = request.post(url, data, timeout=kwargs.get('timeout'))
  File "/usr/local/lib/python3.5/site-packages/telegram/utils/request.py", line 235, in post
    **urlopen_kwargs)
  File "/usr/local/lib/python3.5/site-packages/telegram/utils/request.py", line 178, in _request_wrapper
    raise Unauthorized()
telegram.error.Unauthorized: Unauthorized

2016-08-17 11:42:44,322 - telegram.ext.dispatcher - CRITICAL - stopping due to exception in another thread
```

**Comment by eugenio412** [comment]
I guess Python-telegram-bot doesn't support Python 3.5, try with Python 3.4 and let me know

**Comment by mmenanno** [comment]
hmmmm, not sure how to do that. I'm on a mac and i know via homebrew i'm able to have the latest version of python 2 and python 3 but not sure how to do other versions.

**Comment by mmenanno** [comment]
According to their github page they should support python 2.6 through to 3.5
https://github.com/python-telegram-bot/python-telegram-bot

**Comment by darthvectivus** [comment]
same here, tried with python3.4 and python3.5... same error

**Comment by eugenio412** [comment]
The error Unauthorized came out when the bot has been blocked, maybe you deleted the chat and stopped the bot at the same time. Try to see in your blocked contacts on telegram and see if your bot is blocked. 
@halorrr @darthvectivus let me know if that's the problem

**Comment by darthvectivus** [comment]
i restart the whole process and it work. I think its might be related to the token, maybe ive got it wrong the first time. thanks

**Comment by eugenio412** [comment]
Good to know @darthvectivus , and how is it going there @halorrr ?

**Comment by mmenanno** [comment]
Restarted the whole process as well and it now works here too. The only thing i might have done differently thinking back is i may have started the bot in telegram before running the bot from python. So that might have been what happened.

**Comment by eugenio412** [comment]
Might be, I hope it's going to work just fine, on the contrary of pogom, I'm having so many ban that it's not usable anymore

**Comment by Unknown66** [comment]
You've got to shutdown pogom over night that helps! And delete all banned accounts before restarting.
