### ISSUE TITLE
Unable To Open Database

### ISSUE THREAD

**Issue by mmenanno** [eugenio412/PogomBOT#20]
Back with a new error not that I have the bot running. As soon as I add pokemon I get this.

```
2016-08-19 19:33:20,189 - __main__ - INFO - [237389228] Checking alarm.
2016-08-19 19:33:20,189 - __main__ - INFO - [237389228] Checking pokemon and sending notifications.
2016-08-19 19:33:20,189 - JobQueue - ERROR - An uncaught error was raised while executing job alarm
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/telegram/ext/jobqueue.py", line 128, in tick
    job.run(self.bot)
  File "/usr/local/lib/python3.5/site-packages/telegram/ext/jobqueue.py", line 233, in run
    self.callback(bot, self)
  File "pogobot.py", line 196, in alarm
    checkAndSend(bot, chat_id, search_ids[chat_id])
  File "pogobot.py", line 230, in checkAndSend
    cur.execute(sqlquery)
sqlite3.OperationalError: unable to open database file
```

**Comment by Unknown66** [comment]
Did you copy pogobot.py into the pogom folder?
If so could you please do `ls -lah` from inside pogom folder and post the output here.

**Comment by mmenanno** [comment]
yes i did

```
total 20496
drwxr-xr-x  24 user  staff   816B 19 Aug 18:59 .
drwxr-xr-x+ 61 user  staff   2.0K 19 Aug 18:58 ..
-rw-r--r--@  1 user  staff    10K 19 Aug 18:59 .DS_Store
drwxr-xr-x  15 user  staff   510B 19 Aug 19:29 .git
-rw-r--r--   1 user  staff   609B 18 Aug 21:09 .gitignore
-rw-r--r--   1 user  staff     6B 17 Aug 11:26 .python-version
-rw-r--r--   1 user  staff   569B  9 Aug 14:09 Dockerfile
-rw-r--r--   1 user  staff   462B  9 Aug 14:09 ISSUE_TEMPLATE.md
-rw-r--r--   1 user  staff   1.0K  9 Aug 14:09 LICENSE
-rw-r--r--   1 user  staff   5.4K 19 Aug 09:47 README.md
-rw-r--r--@  1 user  staff    93B 19 Aug 19:01 config-bot.json
-rw-r--r--   1 root            staff   3.5K 19 Aug 19:27 config.json
-rw-r--r--   1 user  staff   3.2K 17 Aug 10:15 deploy-to-jelastic.png
-rw-r--r--   1 user  staff   1.8K 17 Aug 10:15 icon-32x32.png
-rw-r--r--   1 user  staff   611B 17 Aug 10:15 manifest.jps
-rw-r--r--   1 user  staff    10K 19 Aug 18:58 pogobot.py
drwxr-xr-x  16 user  staff   544B 19 Aug 09:47 pogom
-rw-r--r--   1 root            staff   5.9M 19 Aug 21:15 pogom.db
-rw-r--r--   1 root            staff    32K 19 Aug 19:30 pogom.db-shm
-rw-r--r--   1 root            staff   4.0M 19 Aug 21:16 pogom.db-wal
-rw-r--r--   1 user  staff   292B  9 Aug 14:09 requirements.txt
-rw-r--r--   1 user  staff   2.7K 18 Aug 21:09 runserver.py
drwxr-xr-x  13 user  staff   442B 18 Aug 21:09 static
drwxr-xr-x   6 user  staff   204B 18 Aug 21:09 templates
```

**Comment by Unknown66** [comment]
The database `pogom.db` belongs to root thats why it can't open.

Two solution:
1. chown user:user pogom.db\* config.json and run runservery.py without root
2. run pogobot.py with sudo

Please tell me if it helped. :1234:

**Comment by mmenanno** [comment]
I used the chown and it works beautifully now, thanks!
