### ISSUE TITLE
[Feature Request] - Reconnect to MySQL automatically

### ISSUE THREAD

**Issue by pki0** [eugenio412/PogomBOT#67]
## Checklist
- [x] I've read the [WIKI](https://github.com/eugenio412/pogomBOT/wiki)
- [x] I have checked if this issue already exists (both open and closed issues)
- [x] I am using the most recent version of pogomBOT from the master branch
- [x] If this is an installation issue, I am posting my OS, OS version, python version, pip version
- [x] I'm posting the complete log, best if using pastebin for long outputs
- [x] I'm using a descriptive title for this issue
## My Issue

When you loose the connection to MySQL (e.g. restart mysql or internet connection lost) the bot stops working. 

Would be great if you can add a reconnect feature.

**Comment by Unknown66** [comment]
Hey,

could you open an issue for each one please? :-)
That makes it more clear for others to read.

**Comment by Unknown66** [comment]
Okay one question is there any error if the connection is lost?

**Comment by pki0** [comment]
2016-09-30 16:45:28,910 - **main**:371 - INFO - [-150488203] Checking alarm.
2016-09-30 16:45:28,910 - **main**:398 - INFO - [-150488203] Checking pokemon and sending notifications.
2016-09-30 16:45:28,910 - **main**:467 - ERROR - [-150488203] OperationalError(2006, "MySQL server has gone away (BrokenPipeError(32, 'Broken pipe'))")
2016-09-30 16:45:28,910 - JobQueue:132 - ERROR - An uncaught error was raised while executing job alarm
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/telegram/ext/jobqueue.py", line 128, in tick
    job.run(self.bot)
  File "/usr/local/lib/python3.4/dist-packages/telegram/ext/jobqueue.py", line 233, in run
    self.callback(bot, self)
  File "pogobot.py", line 372, in alarm
    checkAndSend(bot, chat_id, prefs.get(chat_id).get('search_ids'))
  File "pogobot.py", line 468, in checkAndSend
    lock.release()
RuntimeError: release unlocked lock
2016-09-30 16:45:58,911 - **main**:371 - INFO - [-150488203] Checking alarm.
2016-09-30 16:45:58,911 - **main**:398 - INFO - [-150488203] Checking pokemon and sending notifications.
2016-09-30 16:45:58,911 - **main**:467 - ERROR - [-150488203] OperationalError(2006, "MySQL server has gone away (BrokenPipeError(32, 'Broken pipe'))")
2016-09-30 16:45:58,911 - JobQueue:132 - ERROR - An uncaught error was raised while executing job alarm
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/telegram/ext/jobqueue.py", line 128, in tick
    job.run(self.bot)
  File "/usr/local/lib/python3.4/dist-packages/telegram/ext/jobqueue.py", line 233, in run
    self.callback(bot, self)
  File "pogobot.py", line 372, in alarm
    checkAndSend(bot, chat_id, prefs.get(chat_id).get('search_ids'))
  File "pogobot.py", line 468, in checkAndSend
    lock.release()
RuntimeError: release unlocked lock

No notifications when this happens. I restarted the mysqlserver at 16:35

**Comment by Unknown66** [comment]
Okay should be possible to fix it then 👍

**Comment by Unknown66** [comment]
Okay I checked it's possible to fix it!

I will fit it this weekend if I've got some time else next week.

**Comment by pki0** [comment]
Nice to hear. Thanks a lot!

**Comment by Unknown66** [comment]
Should be fixed on develop branch now!
You can test it if you've got the time 👍 

Commit 2dd1575d4c30377d30dfd8d89042f93f7e30147c.
