### ISSUE TITLE
Notifications not sent to all users/groups

### ISSUE THREAD

**Issue by Korzakov** [eugenio412/PogomBOT#9]
I have a bot running for myself and a couple of friends. I really like the bot, awesome software.
But it seems were having an issue with the notifications. We have a group with all friends, where the bot is part of. We set notifications for category 3,4 and 5. We're not receiving all notifications. The more rare are received, but some less rare like Kakuna are not (always received). I can not really find out whats wrong.

Is the bot able to handle notifications to groups and users with separate scanlists?

**Comment by Korzakov** [comment]
Now looking at the logs, i see many errors like this:

2016-08-18 20:16:31,151 - JobQueue - ERROR - An uncaught error was raised while executing job rarityalarm
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/telegram/ext/jobqueue.py", line 128, in tick
    job.run(self.bot)
  File "/usr/local/lib/python3.4/dist-packages/telegram/ext/jobqueue.py", line 233, in run
    self.callback(bot, self)
  File "pogobot.py", line 104, in rarityalarm
    bot.sendVenue(job.context[0], latitude, longitude, title, address)
  File "/usr/local/lib/python3.4/dist-packages/telegram/bot.py", line 121, in decorator
    result = func(self, _args, *_kwargs)
  File "/usr/local/lib/python3.4/dist-packages/telegram/bot.py", line 147, in decorator
    result = request.post(url, data, timeout=kwargs.get('timeout'))
  File "/usr/local/lib/python3.4/dist-packages/telegram/utils/request.py", line 235, in post
    **urlopen_kwargs)
  File "/usr/local/lib/python3.4/dist-packages/telegram/utils/request.py", line 178, in _request_wrapper
    raise Unauthorized()

I think this may have caused these issues?

**Comment by Unknown66** [comment]
Okay that error tells me nothing.
But the bot is saving which pokemon has been sent without per user basis.
If my pull request gets merged I will see if I can change this behavior tomorrow.

**Comment by eugenio412** [comment]
@Korzakov let me know if the new merge of @Unknown66 you still have this problem. 

By the way when you see "Unuthorized" it means that some of your friends blocked the bot. So ask them if they delete the chat with your bot, maybe they still have it in the blocked accounts.

**Comment by Unknown66** [comment]
Yes still have this problem I can tell you. I will fix this tonight! If you want you can assign me this issue and #11.
